"""create plot geometries and history tables

Revision ID: 9cd5f8362b0b
Revises: 
Create Date: 2026-05-28 11:18:36.182900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cd5f8362b0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plot_geometries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('external_plot_id', sa.Integer(), nullable=False),
    sa.Column('polygon_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_geometries_project_id'), 'plot_geometries', ['project_id'], unique=False)
    op.create_table('geometry_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_geometry_id', sa.UUID(), nullable=False),
    sa.Column('polygon_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plot_geometry_id'], ['plot_geometries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geometry_history_plot_geometry_id'), 'geometry_history', ['plot_geometry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geometry_history_plot_geometry_id'), table_name='geometry_history')
    op.drop_table('geometry_history')
    op.drop_index(op.f('ix_plot_geometries_project_id'), table_name='plot_geometries')
    op.drop_table('plot_geometries')
    # ### end Alembic commands ###
